parameters:
#    kunstmaan_admin_node.example.class: Kunstmaan\AdminNodeBundle\Example

services:
#    kunstmaan_admin_node.example:
#        class: %kunstmaan_admin_node.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    node.listener:
         class: Kunstmaan\AdminNodeBundle\Listener\NodeGenerator
         tags:
                - { name: doctrine.event_listener, event: postUpdate, method: postUpdate }
                - { name: doctrine.event_listener, event: postPersist, method: postPersist }
                - { name: doctrine.event_listener, event: prePersist, method: prePersist }
                - { name: doctrine.event_listener, event: preRemove, method: preRemove }
                - { name: doctrine.event_listener, event: postLoad, method: postLoad }

    kunstmaan_node.pages_menu:
        class: Kunstmaan\AdminNodeBundle\Helper\Menu\PageMenuAdaptor
        arguments: ["@knp_menu.factory"]